INSERT INTO users (username, email, hashed_password, firstname, lastname, zipcode, about, profile_pic) 
VALUES
('demouser', 'demo@demo.com', 'password', 'demo', 'user', '33467', 'If youre sacred jump in my pocket', 'https://pbs.twimg.com/profile_images/1036730403514736650/PCRxFiEt_400x400.jpg'),
('elonmusk', 'elon@spacex.com', 'password', 'Elon', 'Musk', '77562', 'I like to dream big!', 'https://pbs.twimg.com/profile_images/1295975423654977537/dHw9JcrK_400x400.jpg'),
('mfdoom', 'mfdoom@life.com', 'password', 'MF', 'Doom', '65373', 'Daniel Dumile DOOM-ee-lay, better known by several stage names, most notably MF Doom, is a British rapper, songwriter, and record producer.', 'https://www.gstatic.com/tv/thumb/persons/1021025/1021025_v9_ba.jpg'),
('rrf4', 'reed@f4.com', 'password', 'Reed', 'Richards', '87323', 'Richards possesses a mastery of mechanical, aerospace and electrical engineering, chemistry, all levels of physics, and human and alien biology.', 'https://images-na.ssl-images-amazon.com/images/I/51tG%2BuOuXqL._AC_SX425_.jpg'),
('supremepizza', 'pizzasupreme@green.com', 'password', 'Vermin', 'Supreme', '99654', 'He currently serves as a member of the Libertarian Partys judicial committee.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Vermin_Supreme_August_2019.jpg/1200px-Vermin_Supreme_August_2019.jpg'),
('albercamus', 'isthereapoint@pushtherock.com', 'password', 'Albert', 'Camus', '14986', 'He won the Nobel Prize in Literature at the age of 44 in 1957, the second-youngest recipient in history.', 'https://miro.medium.com/max/900/1*9NfF1Q4cPyO7ZLpCFJh6OA.jpeg')
;

INSERT INTO tweets (user_id, content, media) 
VALUES 
(1, 'My sister is so embarrassing, and I want to dream bigger. For all funky fluff, in the end. #cheapbling #randomtweet', 'http://placeimg.com/640/480/any'),
(1, 'My smile is fantastic, and I want to go to Mars. Here is to more cowards, strictly speaking. #sometrain #randomtweet', 'http://placeimg.com/640/480/any'),
(1, 'hi, grandma? can u come pick me up from my rap battle? its over. no, i lost. he saw u drop me off &amp; did a pretty devastating rhyme about it', 'http://placeimg.com/640/480/any'),
(1, 'The owner of my AirBnB has a dog named Kevin. His human-sounding name terrified me at first.', 'http://placeimg.com/640/480/any'),
(1, 'MY DENTIST ASKED HIS ASSISTANT TO SUCTION (THE WATER OUT OF MY MOUTH)BUT I THOUGHT HE WAS TALKING TO ME SO I SUCKED HIS FINGER. IM MORTIFIED', 'http://placeimg.com/640/480/any'),
(1, 'I like it when they put "the end" after a movie, so that you know not to stay sat in your seat for the rest of your life.', 'http://placeimg.com/640/480/any'),
(1, 'Lord give me the commitment of a guy they forced into a polar bear costume going full method during an escape drill ', 'http://placeimg.com/640/480/any'),
(1, 'FIRST PERSON TO GET A CAT: haha this thing is an asshole I’m gonna keep it', 'http://placeimg.com/640/480/any'),
(1, 'Social best research wish particularly customer fine.', 'http://placeimg.com/640/480/any'),
(1, 'Rich the land nothing everything safe not.', 'http://placeimg.com/640/480/any'),
(2, 'Back sing door season want west group.', 'http://placeimg.com/640/480/any'),
(2, 'Know own specific good.', 'http://placeimg.com/640/480/any'),
(2, 'Test ok individual compare pass.', 'http://placeimg.com/640/480/any'),
(2, 'Series Mrs administration decision.', 'http://placeimg.com/640/480/any'),
(2, 'Each window major live time experience.', 'http://placeimg.com/640/480/any'),
(2, 'Response live nor right simple main head.', 'http://placeimg.com/640/480/any'),
(2, 'My employee simple week.', 'http://placeimg.com/640/480/any'),
(2, 'Your end letter.', 'http://placeimg.com/640/480/any'),
(2, 'Shoulder your our international.', 'http://placeimg.com/640/480/any'),
(2, 'Fill wind above goal.', 'http://placeimg.com/640/480/any'),
(3, 'Benefit race law enjoy during suffer design.', 'http://placeimg.com/640/480/any'),
(3, 'My expert product fish.', 'http://placeimg.com/640/480/any'),
(3, 'Rise build guy lead.', 'http://placeimg.com/640/480/any'),
(3, 'Themselves central side increase million citizen.', 'http://placeimg.com/640/480/any'),
(3, 'School factor ago any wind.', 'http://placeimg.com/640/480/any'),
(3, 'Walk culture fear east political.', 'http://placeimg.com/640/480/any'),
(3, 'Answer a mission worker.', 'http://placeimg.com/640/480/any'),
(3, 'Series leg always law behavior citizen form.', 'http://placeimg.com/640/480/any'),
(3, 'Nearly require training second throughout many.', 'http://placeimg.com/640/480/any'),
(3, 'Political cultural point able leader almost few person.', 'http://placeimg.com/640/480/any'),
(4, 'Marriage name because agency election.', 'http://placeimg.com/640/480/any'),
(4, 'Herself large performance enough must drop raise.', 'http://placeimg.com/640/480/any'),
(4, 'Avoid attack road blood.', 'http://placeimg.com/640/480/any'),
(4, 'Author life maintain lose perhaps late.', 'http://placeimg.com/640/480/any'),
(4, 'Moment southern capital Democrat tend.', 'http://placeimg.com/640/480/any'),
(4, 'Simply feeling community brother tonight pick.', 'http://placeimg.com/640/480/any'),
(4, 'Beat employee particular behavior room fish course.', 'http://placeimg.com/640/480/any'),
(4, 'Bring they Mr read.', 'http://placeimg.com/640/480/any'),
(4, 'Suddenly data party throughout do.', 'http://placeimg.com/640/480/any'),
(5, 'Behavior very reality a especially movie address.', 'http://placeimg.com/640/480/any'),
(5, 'Teach throughout full though voice share.', 'http://placeimg.com/640/480/any'),
(5, 'Share whether themselves sometimes research.', 'http://placeimg.com/640/480/any'),
(5, 'Special along gun society.', 'http://placeimg.com/640/480/any'),
(5, 'Per end color president.', 'http://placeimg.com/640/480/any'),
(5, 'Send major positive year do successful war five.', 'http://placeimg.com/640/480/any'),
(5, 'Avoid ready tend capital but seat.', 'http://placeimg.com/640/480/any'),
(5, 'Like feeling if side.', 'http://placeimg.com/640/480/any'),
(5, 'Last notice meet many view film.', 'http://placeimg.com/640/480/any'),
(6, 'Best front hot talk history stop.', 'http://placeimg.com/640/480/any'),
(6, 'Defense population evening position dinner method.', 'http://placeimg.com/640/480/any'),
(6, 'Interest south site election scientist star church.', 'http://placeimg.com/640/480/any'),
(6, 'Big country food security.', 'http://placeimg.com/640/480/any'),
(6, 'Its every network check probably.', 'http://placeimg.com/640/480/any'),
(6, 'Operation list pick result.', 'http://placeimg.com/640/480/any'),
(6, 'Join use several spend.', 'http://placeimg.com/640/480/any'),
(6, 'Site gun provide American she.', 'http://placeimg.com/640/480/any'),
(6, 'Condition federal executive.', 'http://placeimg.com/640/480/any'),
(6, 'About mind ahead western president.', 'http://placeimg.com/640/480/any'),
(6, 'Citizen wait young help affect until.', 'http://placeimg.com/640/480/any'),
(6, 'Education management state sing box area.', 'http://placeimg.com/640/480/any')