"""trap migration

Revision ID: 0806544b51f0
Revises: 
Create Date: 2020-08-29 22:53:07.088329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0806544b51f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashedpassword', sa.Binary(), nullable=False),
    sa.Column('firstname', sa.String(length=40), nullable=False),
    sa.Column('lastname', sa.String(length=40), nullable=False),
    sa.Column('zipcode', sa.Integer(), nullable=False),
    sa.Column('pinnedtweet', sa.Integer(), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('profilepic', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('firstname'),
    sa.UniqueConstraint('hashedpassword'),
    sa.UniqueConstraint('lastname'),
    sa.UniqueConstraint('username')
    )
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('followingid', sa.Integer(), nullable=False),
    sa.Column('followerid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followerid'], ['users.id'], ),
    sa.ForeignKeyConstraint(['followingid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tweets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appuserid', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('retweetedtweetid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appuserid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appuserid', sa.Integer(), nullable=False),
    sa.Column('liketweetid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appuserid'], ['users.id'], ),
    sa.ForeignKeyConstraint(['liketweetid'], ['tweets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appuserid', sa.Integer(), nullable=False),
    sa.Column('tweetid', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['appuserid'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tweetid'], ['tweets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replies')
    op.drop_table('likes')
    op.drop_table('tweets')
    op.drop_table('follows')
    op.drop_table('users')
    # ### end Alembic commands ###
